name: Deploy Run Report Maker Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Execute deployment script on Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/${{ secrets.SERVER_USERNAME }}/run_report_maker_bot
          chmod +x deploy_run_report_maker_bot.sh
          ./deploy_run_report_maker_bot.sh ${{ secrets.SERVER_USERNAME }}
